# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("DynMultiply"); Pkg.test("DynMultiply"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("DynMultiply")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
